image:
  repository: jshreyash/flask-hello-world
  tag: v1.0.40
  pullPolicy: IfNotPresent

replicaCount: 3

service:
  type: LoadBalancer
  port: 80
  targetPort: 5000

app:
  name: flask-app
  port: 5000